<?php

namespace Virgule\Bundle\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\Query;

/**
 * ClassSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassSessionRepository extends EntityRepository {
    
     public function loadAllClassSessionByTeacher($teacherId, $limit=5) {
        $q = $this
            ->createQueryBuilder('c')
            ->addSelect('c.id, c.date, count(cm.id) as nb_comments')
            ->innerJoin('c.sessionTeacher', 't')
            ->leftJoin('c.comments', 'cm')
            ->where('t.id = :teacherId')
            ->setParameter('teacherId', $teacherId)
            ->setMaxResults($limit) 
            ->add('orderBy', 'c.date DESC')
            ->add('groupBy', 'c.id')
            ->getQuery()
        ;
        $results = $q->execute(array(), Query::HYDRATE_ARRAY);
        return $results;   
    }
    
    public function loadLatest($limit = 5) {
        $q = $this
            ->createQueryBuilder('c')
            ->addSelect('c.id, c.date, count(cm.id) as nb_comments')
            ->leftJoin('c.comments', 'cm')
            ->setMaxResults($limit) 
            ->add('orderBy', 'c.date DESC')
            ->add('groupBy', 'c.id')
            ->getQuery()
        ;
        $results = $q->execute(array(), Query::HYDRATE_ARRAY);
        return $results;  
    }
    
}
