<?php

namespace Virgule\Bundle\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\Query;

/**
 * ClassSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassSessionRepository extends EntityRepository {
    
     public function loadAllClassSessionByTeacher($semesterId, $teacherId, $limit=5) {
        $q = $this
            ->createQueryBuilder('c')
            ->addSelect('c.id, c.date, count(cm.id) as nb_comments')
            ->innerJoin('c.sessionTeacher', 't')
            ->leftJoin('c.comments', 'cm')
            ->where('t.id = :teacherId')
            ->setParameter('teacherId', $teacherId)
            ->setMaxResults($limit) 
            ->add('orderBy', 'c.date DESC')
            ->add('groupBy', 'c.id')
            ->getQuery()
        ;
        $results = $q->execute(array(), Query::HYDRATE_ARRAY);
        return $results;   
    }
    
    public function loadAll($semesterId, $limit = null) {
        $qb = $this
            ->createQueryBuilder('c')
            ->addSelect('c.id as id, c.date as date, count(cm.id) as nb_comments, c2.id as course_id, c2.dayOfWeek as course_dayOfWeek,
                c2.startTime as course_startTime, c2.endTime as course_endTime,
                t.id as sessionTeacher_id, t.firstName as sessionTeacher_firstName, t.lastName as sessionTeacher_lastName'
                    )
            ->innerJoin('c.course', 'c2')
            ->innerJoin('c.sessionTeacher', 't')
            ->leftJoin('c.comments', 'cm')        
            ->add('orderBy', 'c.date DESC')
            ->add('groupBy', 'c.id');
        
            if ($limit != null) {
                $qb->setMaxResults($limit);
            }
        
         $q = $qb->getQuery()
        ;
        $results = $q->execute(array(), Query::HYDRATE_ARRAY);
        return $results;  
    }
    
}
