<?php

namespace Virgule\Bundle\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\Query;
use Doctrine\DBAL\Types\Type;
/**
 * ClassRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassRoomRepository extends EntityRepository {
    
    private function createDefaultQueryBuilder() {
        return $this->createQueryBuilder('cr')->add('orderBy', 'cr.id');
    }
    
    public function getClassRoomsForOrganizationBranch($organizationBranchId) {
        $qb = $this->createDefaultQueryBuilder()
                ->select('cr.id as classroom_id, cr.name as classroom_name, cr.comments as classroom_comments')
                ->innerJoin('cr.organizationBranch' , 'ob')
                ->where('ob.id = :organizationBranchId')
                ->setParameter('organizationBranchId', $organizationBranchId);
        
        $q = $qb->getQuery();
        $students = $q->execute(array(), Query::HYDRATE_ARRAY);
        return $students;
    }
}
