<?php

namespace Virgule\Bundle\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository {
    
    public function loadLatestRelatedToTeacher(Array $classSessionIds, Array $studentIds) {
        $classSessionIds = implode(',',$classSessionIds);
        $studentIds = implode(',',$studentIds);
        
        $q = $this
            ->createQueryBuilder('c')
            ->addSelect('c.id, c.date')
            ->leftJoin('c.student', 's', 'WITH', 's.id IN (:studentIds)')
            ->leftJoin('c.classsession', 'cs', 'WITH', 'cs.id IN (:classSessionIds)')
            ->where('s.id IN (:studentIds)')
            ->orWhere('cs.id IN (:classSessionIds)')
            ->add('orderBy', 's.date DESC')
            ->setParameter('classSessionIds', $classSessionIds)
            ->setParameter('studentIds', $studentIds)
            ->getQuery()
        ;
        $comments = $q->execute(array(), Query::HYDRATE_ARRAY);
        return $comments;   
    }
}
