<?php

namespace Virgule\Bundle\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository {
        
    public function createDefaultQueryBuilder() {
        return $this->createQueryBuilder('c')->add('orderBy', 'c.label ASC');
    }
    
    public function loadAllQueryBuilder() {
        $qb = $this->createDefaultQueryBuilder();
        return $qb;
    }
    
    public function loadAll() {
        $q = $this->loadAllQueryBuilder()
            ->getQuery();
        
        return $q->execute();
    }
    
}
