<?php

namespace Virgule\Bundle\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\Query;
use Doctrine\DBAL\Connection;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends EntityRepository {

    private function createDefaultQueryBuilder() {
        return $this->createQueryBuilder('sl')->add('orderBy', 'sl.name ASC');
    }

    public function findAll() {
        return $this->findBy(array(), array('name' => 'asc'));
    }

    public function getNumberOfLanguagesSpoken($semesterId) {
        $qb = $this->createDefaultQueryBuilder();
        
        $qb     
                ->select($qb->expr()->countDistinct('s.id'). ' AS nb_students')
                ->addSelect('sl.name as language_name')
                ->innerJoin('sl.students', 's')
                ->innerJoin('s.courses', 'c')
                ->where('c.semester = :semesterId')
                ->groupBy('sl.id')
                ->orderby('nb_students', 'DESC')
                ->setParameter('semesterId', $semesterId);

        $q = $qb->getQuery();
        $languages = $q->execute(array(), Query::HYDRATE_ARRAY);
        return $languages;
    }

}
