<?php

namespace Virgule\Bundle\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpenHouseRepository extends EntityRepository {
    
    public function createDefaultQueryBuilder() {
        return $this->createQueryBuilder('oh')->add('orderBy', 'oh.date ASC');
    }
    
    public function loadAllForSemesterQueryBuilder($semesterId) {
        $qb = $this->createDefaultQueryBuilder()
                ->where('oh.semester = :semesterId')
                ->setParameter('semesterId', $semesterId);
        return $qb;
    }
    
    public function loadAllForSemester($semesterId) {
        $q = $this->loadAllForSemesterQueryBuilder($semesterId)
            ->getQuery();
        
        return $q->execute();
    }
}
