<?php

namespace Virgule\Bundle\MainBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * TeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationBranchRepository extends EntityRepository {
    
    public function getBranchesNames() {
        $entities = $em->getRepository('VirguleMainBundle:Teacher')->findAll();
    }    
}

?>
