<?php

namespace Virgule\Bundle\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\Query;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository {

    private function createDefaultQueryBuilder() {
        return $this->createQueryBuilder('s');
    }
    
    public function getBasicQueryBuilder() {
        $qb = $this
            ->createDefaultQueryBuilder()
            ->addSelect('s.id, s.firstname as firstname, s.lastname as lastname, s.gender as gender, s.phoneNumber as phoneNumber, s.cellphoneNumber')
            ->addSelect('c.isoCode, c.label')
            ->innerJoin('s.nativeCountry', 'c')
            ->add('orderBy', 's.lastname ASC, s.firstname ASC');
        return $qb;
    }
    
    /**
     * Select all students enrolled in a class of the selected semester
     * @return type
     */
    public function loadAll($semesterId) {
        $q = $this->getBasicQueryBuilder()
                ->addSelect('t.id as teacher_id, t.firstName as teacher_firstName, t.lastName as teacher_lastName, count(cm.id) as nb_comments, s.registrationDate')
                ->addSelect('c2.id as course_id, l.label as level')
                ->innerJoin('s.courses', 'c2')
                ->innerJoin('c2.classLevel', 'l')
                ->leftJoin('s.welcomedByTeacher', 't')
                ->leftJoin('s.comments', 'cm')
                ->where('c2.semester = :semesterId')
                ->add('orderBy', 's.lastname ASC, s.firstname ASC')
                ->add('groupBy', 's.id')
                ->setParameter('semesterId', $semesterId)
                ->getQuery()
        ;
        $students = $q->execute(array(), Query::HYDRATE_ARRAY);
        return $students;
    }
    
    public function getQueryBuilderForStudentEnrolledInCourses(Array $courseIds) {
        $ids = implode(',', $courseIds);
        $q = $this
                ->createDefaultQueryBuilder()
                ->innerJoin('s.courses', 'c2', 'WITH', 'c2.id IN (:coursesIds)')
                ->setParameter('coursesIds', $ids)
        ;
        return $q;
    }

    public function loadAllEnrolledInCourses(Array $courseIds) {
        $q = $this->getQueryBuilderForStudentEnrolledInCourses($courseIds);
        return $q->getQuery()->execute(array(), Query::HYDRATE_ARRAY);
    }
    
    /**
     * 
     * @param array $courseIds
     * @return type
     */
    public function loadAllEnrolledInCourse($courseId) {
        return $this->loadAllEnrolledInCourses(Array($courseId));
    }

    public function loadAllPresentAtClassSession($classSessionId) {
        $q = $this->getBasicQueryBuilder()
                ->innerJoin('s.classSessions', 'cs')
                ->where('cs.id = :classSessionId')
                ->setParameter('classSessionId', $classSessionId);
        
        return $q->getQuery()->execute(array(), Query::HYDRATE_ARRAY);
    }
    
    public function getStudentsInformation($semesterId) {
        $q = $this
                ->createDefaultQueryBuilder()
                ->addSelect('s.id as student_id, s.gender as student_gender')
                ->addSelect('c1.isoCode as country_code, c1.label as country_label')
                ->innerJoin('s.nativeCountry', 'c1')
                ->innerJoin('s.courses', 'c2')
                ->where('c2.semester = :semesterId')
                ->setParameter('semesterId', $semesterId)
                ->distinct()
                ->getQuery()
        ;
        $students = $q->execute(array(), Query::HYDRATE_ARRAY);
        return $students;
    }
}