<?php

namespace Virgule\Bundle\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository {
    private function createDefaultQueryBuilder() {
        return $this->createQueryBuilder('t')->add('orderBy', 't.label ASC');
    }
    
    public function getTagByLabel($tagLabel) {
        $qb = $this->createDefaultQueryBuilder()
            ->where('t.label = :tagLabel')
            ->setParameter('tagLabel', $tagLabel);
        
        return $qb->getQuery()->getOneOrNullResult();
    }
}
