Processing entity "Apprenants"
Processing entity "Cours"
Processing entity "Delegations"
Processing entity "Formateurs"
Processing entity "Langues"
Processing entity "LogActions"
Processing entity "Niveaux"
Processing entity "Pays"
Processing entity "Permissions"
Processing entity "RaisonsApprentissage"
Processing entity "Salles"
Processing entity "Seances"
Processing entity "Sessions"

Exporting "xml" mapping information to "/var/www/html/Virgule/src/Virgule/Bundle/MainBundle/Resources/config/doctrine/metadata/orm"
